import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { details, mockApi, products } from './api'

const searchName = 'Buscar por marca o modelo'
const counter = (page: Page, count: number) => page.getByLabel(`Cesta: ${count} productos`)
async function checkAccessibility(page: Page) {
  // axe calcula colores renderizados; esperar las entradas evita medir un fundido intermedio.
  for (const element of await page.locator('.catalog-page, .catalog-results, .detail-enter').all()) {
    await expect(element).toHaveCSS('opacity', '1')
  }
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(result.violations).toEqual([])
}
async function checkOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
}

test('listado → búsqueda → detalle → selección → cesta → navegación → recarga', async ({ page }) => {
  const calls = await mockApi(page)
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true })).toBeVisible()
  await page.evaluate(() => Reflect.set(window, 'documentMarker', 'same-document'))
  await expect(page.getByRole('list', { name: 'Productos' }).getByRole('link')).toHaveCount(products.length)
  await expect(page.getByText('Precio no disponible', { exact: true })).toBeVisible()
  const search = page.getByRole('searchbox', { name: searchName })
  await search.fill('  aCeR  ')
  await expect(page.getByRole('list', { name: 'Productos' }).getByRole('link')).toHaveCount(3)
  await search.fill(' TALK ')
  await expect(page.getByRole('list', { name: 'Productos' }).getByRole('link')).toHaveCount(1)
  expect(calls.list).toBe(1)
  await page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Iconia Talk S' })).toBeVisible()
  expect(await page.evaluate(() => Reflect.get(window, 'documentMarker'))).toBe('same-document')
  await expect(page.getByRole('main')).toBeFocused()
  await expect(page.getByRole('navigation').getByText('Acer Iconia Talk S')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByLabel('Color', { exact: true })).toHaveValue('1000')
  await expect(page.getByRole('button', { name: 'Añadir', exact: true })).toBeDisabled()
  await page.getByLabel('Almacenamiento', { exact: true }).selectOption('2001')
  await page.getByRole('button', { name: 'Añadir', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Producto añadido' })).toBeVisible()
  await expect(counter(page, 3)).toBeVisible()
  expect(calls.cart).toEqual([{ id: details[0].id, colorCode: 1000, storageCode: 2001 }])
  await page.getByRole('navigation').getByRole('link', { name: 'Listado' }).click()
  await expect(counter(page, 3)).toBeVisible()
  await page.reload()
  await expect(page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true })).toBeVisible()
  await expect(counter(page, 3)).toBeVisible()
  expect(calls.list).toBe(1)
  expect(calls.cart).toHaveLength(1)
})

test('error de cesta conserva contador y permite únicamente reintento manual', async ({ page }) => {
  const calls = await mockApi(page, { cartError: true })
  await page.goto(`/product/${details[1].id}`)
  await expect(page.getByRole('heading', { name: 'Liquid Z6 Plus' })).toBeVisible()
  await expect(page.getByLabel('Almacenamiento', { exact: true })).toHaveValue('2000')
  await expect(page.getByRole('button', { name: 'Añadir', exact: true })).toBeDisabled()
  await page.getByLabel('Color', { exact: true }).selectOption('1001')
  await page.getByRole('button', { name: 'Añadir', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('El contador no ha cambiado')
  await expect(counter(page, 0)).toBeVisible()
  await checkAccessibility(page)
  expect(calls.cart).toHaveLength(1)
  await page.getByRole('button', { name: 'Añadir', exact: true }).click()
  await expect(counter(page, 3)).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(calls.cart).toEqual(Array(2).fill({ id: details[1].id, colorCode: 1001, storageCode: 2000 }))
})

test('preview admite URL de detalle directa, recarga, historial y expiración exacta', async ({ page }) => {
  const calls = await mockApi(page)
  const response = await page.goto(`/product/${details[0].id}`)
  expect(response?.status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Iconia Talk S' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Iconia Talk S' })).toBeVisible()
  expect(calls.detail).toBe(1)
  await page.getByRole('navigation').getByRole('link', { name: 'Listado' }).click()
  await page.getByRole('link', { name: 'Acer Liquid Z6 Plus', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Liquid Z6 Plus' })).toBeVisible()
  await expect(page.getByLabel('Color', { exact: true })).toHaveValue('')
  await page.goBack()
  await expect(page.getByRole('searchbox', { name: searchName })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'Liquid Z6 Plus' })).toBeVisible()
  expect(calls.detail).toBe(2)
  // Hora controlada: justo expiresAt es inválido. No se espera una hora real.
  const expiresAt = await page.evaluate(id => JSON.parse(localStorage.getItem(`nunegal:query:v1:product:${id}`)!).expiresAt as number, details[1].id)
  await page.addInitScript(timestamp => { Date.now = () => timestamp }, expiresAt)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Liquid Z6 Plus' })).toBeVisible()
  expect(calls.detail).toBe(3)
  expect(calls.list).toBe(1)
})

test('estructura adaptable, controles, mensajes y contraste en ambas vistas', async ({ page }, testInfo) => {
  await mockApi(page)
  await page.goto('/')
  await expect(page.locator('.catalog-results')).toHaveCSS('opacity', '1')
  const columns = await page.locator('ul.product-grid').evaluate(element => getComputedStyle(element).gridTemplateColumns.split(' ').length)
  expect(columns).toBe(testInfo.project.name === 'desktop' ? 4 : testInfo.project.name === 'tablet' ? 2 : 1)
  await checkOverflow(page)
  await checkAccessibility(page)
  await page.screenshot({ path: testInfo.outputPath('listado.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true }).click()
  await expect(page.locator('.detail-enter')).toHaveCSS('opacity', '1')
  const image = await page.locator('.detail-image').boundingBox()
  const description = await page.locator('.detail-description').boundingBox()
  expect(image).not.toBeNull()
  expect(description).not.toBeNull()
  if (testInfo.project.name === 'desktop') expect(description!.x).toBeGreaterThan(image!.x + image!.width)
  else expect(description!.y).toBeGreaterThan(image!.y + image!.height)
  const tab = await page.locator('.detail-back-tab').boundingBox()
  expect(image!.y).toBeGreaterThan(tab!.y + tab!.height)
  await checkOverflow(page)
  await checkAccessibility(page)
  await page.screenshot({ path: testInfo.outputPath('detalle.png'), fullPage: true, animations: 'disabled' })
  await page.getByLabel('Almacenamiento', { exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('selector.png'), animations: 'disabled' })
  await page.keyboard.press('Escape')
})

test('teclado, foco visible, buscador acoplado y movimiento reducido', async ({ page }) => {
  await mockApi(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true })).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Saltar al contenido' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Descubrir el logo oculto' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Nunegal / ITX' })).toBeFocused()
  await page.keyboard.press('Tab')
  const search = page.getByRole('searchbox', { name: searchName })
  await expect(search).toBeFocused()
  await expect(search).toHaveCSS('outline-style', 'solid')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Iconia Talk S' })).toBeVisible()
  await expect(page.getByRole('main')).toBeFocused()
  await expect(page.locator('.detail-enter')).toHaveCSS('animation-name', 'none')
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Color', { exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Almacenamiento', { exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Almacenamiento', { exact: true })).toHaveValue('2000')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Añadir', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(counter(page, 3)).toBeVisible()
  await page.getByRole('navigation').getByRole('link', { name: 'Listado' }).click()
  await expect(page.locator('.catalog-results')).toHaveCSS('opacity', '1')
  await page.evaluate(() => window.scrollTo(0, 700))
  await expect(page.locator('.search-panel')).toHaveAttribute('data-docked', 'true')
  await page.evaluate(() => window.scrollTo(0, 500))
  await expect(page.locator('.search-panel')).toHaveAttribute('data-visible', 'true')
  await search.focus()
  await expect(search).toHaveCSS('outline-style', 'solid')
  await expect(page.locator('.search-panel')).toHaveCSS('opacity', '1')
  await expect(page.locator('.search-panel')).toHaveCSS('animation-name', 'none')
  await checkOverflow(page)
})

test('esqueletos anuncian carga sin movimiento y fallo del listado admite reintento', async ({ page }) => {
  let release!: () => void
  const delayedList = new Promise<void>(resolve => { release = resolve })
  const calls = await mockApi(page, { delayedList, listError: true })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByRole('status', { name: 'Cargando productos' })).toHaveAttribute('aria-busy', 'true')
  expect(await page.locator('.skeleton').first().evaluate(element => getComputedStyle(element, '::after').animationName)).toBe('none')
  await checkAccessibility(page)
  release()
  await expect(page.getByRole('alert')).toContainText('No se pudieron cargar')
  await page.getByRole('button', { name: 'Reintentar' }).click()
  await expect(page.getByRole('link', { name: 'Acer Iconia Talk S', exact: true })).toBeVisible()
  expect(calls.list).toBe(2)
  await page.getByRole('searchbox', { name: searchName }).fill('sin coincidencias')
  await expect(page.getByText('No se encontraron productos. Prueba con otra marca o modelo.')).toBeVisible()
  expect(calls.list).toBe(2)
})

test('breadcrumb largo a 320 px reserva espacio sin tapar contenido', async ({ page }, testInfo) => {
  await mockApi(page)
  await page.setViewportSize({ width: 320, height: 800 })
  const product = { ...details[0], model: 'Modelo de prueba con un nombre muy largo para revisar el salto de líneas en los breadcrumbs' }
  await page.route(`https://itx-frontend-test.onrender.com/api/product/${product.id}`, route => route.fulfill({ json: product }))
  await page.goto(`/product/${product.id}`)
  await expect(page.locator('.detail-enter')).toHaveCSS('opacity', '1')
  const image = await page.locator('.detail-image').boundingBox()
  const tab = await page.locator('.detail-back-tab').boundingBox()
  expect(image!.y).toBeGreaterThan(tab!.y + tab!.height)
  await checkOverflow(page)
  await checkAccessibility(page)
  await page.screenshot({ path: testInfo.outputPath('breadcrumb-largo.png'), animations: 'disabled' })
})

test('añadir pendiente conserva estado al navegar y anuncia éxito en listado', async ({ page }) => {
  const calls = await mockApi(page)
  let release!: () => void
  const pending = new Promise<void>(resolve => { release = resolve })
  let posts = 0
  await page.route('https://itx-frontend-test.onrender.com/api/cart', async route => {
    if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204 })
    posts++
    await pending
    await route.fulfill({ json: { count: 7 } })
  })
  await page.goto(`/product/${details[0].id}`)
  await page.getByLabel('Almacenamiento', { exact: true }).selectOption('2000')
  await page.getByRole('button', { name: 'Añadir', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Añadiendo…' })).toBeDisabled()
  await expect(counter(page, 0)).toBeVisible()
  await page.getByRole('navigation').getByRole('link', { name: 'Listado' }).click()
  release()
  await expect(counter(page, 7)).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Producto añadido' })).toBeVisible()
  await checkAccessibility(page)
  expect(posts).toBe(1)
  expect(calls.cart).toHaveLength(0)
  await page.reload()
  await expect(counter(page, 7)).toBeVisible()
  expect(posts).toBe(1)
})
